export interface IAlbum {
  _id?: string, // id generated by MongoDB
  name: string,
  creator: string,
  description: string,
  drawingIds: string[]; // Type to verify
  members: string[]; // Type will probably be an interface IUserInfos later
  isPrivate: boolean;
}
