export interface IAlbum {
  _id?: string, // id generated by MongoDB
  name: string,
  owner: string,
  description: string,
  drawingIDs: string[]; // Type to verify
  members: string[]; // Type will probably be an interface IUserInfos later
  membershipRequests: string[];
}
