export enum ToolList {
    Pencil = 0,
    Eraser = 1,
    Line = 2,
    Rectangle = 3,
    Ellipse = 4,
    Spray = 5,
    Polygon = 6,
    Pipette = 7,
    SelectionRectangle = 8,
    SelectionEllipse = 9,
    PaintBucket = 10,
    Lasso = 11,
    MoveSelection = 12,
    Undo = 13,
    Redo = 14,
    Stamp = 15,
}
